# Generated by Django 3.1.8 on 2024-03-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devconnector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
